variables:
  GIT_STRATEGY: clone

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - test
  - build
  - publish

image: $SKA_K8S_TOOLS_DEPLOY_IMAGE

# ============================================================================
# Lint Helm chart, build docs and run tests
# ============================================================================

lint:
  stage: test
  script:
    - helm dependency update charts/ska-sdp
    - helm lint charts/ska-sdp

docs:
  stage: test
  except:
    - tags
  image: python:3.9
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week
    when: always

.k8s-test:
  except:
    - tags
  tags:
    - k8srunner
  variables:
    SERVICE_ACCOUNT: ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH
    NAMESPACE: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH
    NAMESPACE_SDP: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-sdp
    RELEASE: test

test:
  extends: .k8s-test
  stage: test
  before_script:
    - apt-get -y update
    - apt-get install -y curl ca-certificates jq --no-install-recommends
  script:
    - kubectl delete namespace ${NAMESPACE} --ignore-not-found
    - kubectl create namespace ${NAMESPACE}
    - kubectl delete namespace ${NAMESPACE_SDP} --ignore-not-found
    - kubectl create namespace ${NAMESPACE_SDP}
    - curl -s https://gitlab.com/ska-telescope/templates-repository/-/raw/master/scripts/namespace_auth.sh | bash -s $SERVICE_ACCOUNT $NAMESPACE $NAMESPACE_SDP || true
    - helm dependency update charts/ska-sdp
    - helm install ${RELEASE} charts/ska-sdp -n ${NAMESPACE} --set helmdeploy.namespace=${NAMESPACE_SDP} --wait
    - kubectl -n ${NAMESPACE} create -f tests/sdp-testing.yaml
    - kubectl -n ${NAMESPACE} wait pod/sdp-testing --for=condition=ready --timeout=300s
    - kubectl cp tests ${NAMESPACE}/sdp-testing:tests
    - kubectl -n ${NAMESPACE} exec sdp-testing -- pytest -vv --gherkin-terminal-reporter --gherkin-terminal-reporter-expanded --junitxml=unit-tests.xml tests
  after_script:
    - mkdir -p build/reports
    - kubectl cp ${NAMESPACE}/sdp-testing:unit-tests.xml build/reports/unit-tests.xml
    - kubectl -n ${NAMESPACE} delete -f tests/sdp-testing.yaml
  environment:
    name: test/$CI_COMMIT_REF_NAME
    kubernetes:
      namespace: $NAMESPACE
    on_stop: test-cleanup
    auto_stop_in: 2 hours
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

test-cleanup:
  extends: .k8s-test
  stage: .post
  when: manual
  script:
    - kubectl delete namespace ${NAMESPACE_SDP} --ignore-not-found
    - kubectl delete namespace ${NAMESPACE} --ignore-not-found
  environment:
    name: test/$CI_COMMIT_REF_NAME
    kubernetes:
      namespace: $NAMESPACE
    action: stop

# ============================================================================
# Package and publish Helm chart
# ============================================================================

.publish:
  stage: publish
  before_script:
    - /usr/local/bin/extract-metadata.sh charts/ska-sdp/MANIFEST.skao.int
  artifacts:
    paths:
      - ska-sdp-*.tgz
    expire_in: 1 week

# Publish development version to GitLab on non-tag commit

publish-dev:
  extends: .publish
  script:
    - version=$(awk '/^version/ {print $2}' charts/ska-sdp/Chart.yaml | tr -d '"')+${CI_COMMIT_SHORT_SHA}
    - helm package charts/ska-sdp --dependency-update --version=${version}
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ska-sdp-${version}.tgz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/ska-sdp/${version}/ska-sdp-${version}.tgz"'
  rules:
    - if: '$CI_COMMIT_TAG == null || $CI_COMMIT_TAG == ""'

# Publish release to artefact repository on tag on default branch

publish-release:
  extends: .publish
  script:
    - helm package charts/ska-sdp --dependency-update
    - curl -u $CAR_HELM_USERNAME:$CAR_HELM_PASSWORD --upload-file ska-sdp-*.tgz $CAR_HELM_REPOSITORY_URL
  only:
    variables:
       - $CI_COMMIT_MESSAGE =~ /^.+$/ # Confirm tag message exists
       - $CI_COMMIT_TAG =~ /^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/ #Confirm semantic versioning of tag
  except:
    - branches

# ============================================================================
# CI metrics
# ============================================================================
# Create Gitlab CI badges from CI metrics
# https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'