variables:
  GIT_STRATEGY: clone

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - test
  - build
  - publish

image: quay.io/helmpack/chart-testing:latest

# ============================================================================
# Lint Helm chart, build docs and run tests
# ============================================================================

lint:
  stage: test
  script:
    - helm lint charts/sdp

docs:
  stage: test
  except:
    - tags
  image: python:latest
  before_script:
    - pip3 install -r docs/requirements.txt
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week
    when: always

.k8s-test:
  image: nexus.engageska-portugal.pt/ska-docker/deploy:0.4.3
  except:
    - tags
  tags:
    - k8srunner
  variables:
    SERVICE_ACCOUNT: ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH
    NAMESPACE: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH
    NAMESPACE_SDP: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-sdp
    RELEASE: test

test:
  extends: .k8s-test
  stage: test
  before_script:
    - apt-get -y update
    - apt-get install -y curl ca-certificates jq --no-install-recommends
  script:
    - kubectl delete namespace ${NAMESPACE} --ignore-not-found
    - kubectl create namespace ${NAMESPACE}
    - kubectl delete namespace ${NAMESPACE_SDP} --ignore-not-found
    - kubectl create namespace ${NAMESPACE_SDP}
    - curl -s https://gitlab.com/ska-telescope/templates-repository/-/raw/master/scripts/namespace_auth.sh | bash -s $SERVICE_ACCOUNT $NAMESPACE $NAMESPACE_SDP || true
    - helm dependency update charts/sdp
    - helm install ${RELEASE} charts/sdp -n ${NAMESPACE} --set helmdeploy.namespace=${NAMESPACE_SDP} --wait
    - kubectl -n ${NAMESPACE} create -f tests/sdp-testing.yaml
    - kubectl -n ${NAMESPACE} wait pod/sdp-testing --for=condition=ready --timeout=300s
    - kubectl cp tests ${NAMESPACE}/sdp-testing:tests
    - kubectl -n ${NAMESPACE} exec sdp-testing -- pytest -vv --gherkin-terminal-reporter --gherkin-terminal-reporter-expanded --junitxml=unit-tests.xml tests
  after_script:
    - mkdir -p build/reports
    - kubectl cp ${NAMESPACE}/sdp-testing:unit-tests.xml build/reports/unit-tests.xml
    - kubectl -n ${NAMESPACE} delete -f tests/sdp-testing.yaml
  environment:
    name: test/$CI_COMMIT_REF_NAME
    kubernetes:
      namespace: $NAMESPACE
    on_stop: test-cleanup
    auto_stop_in: 2 hours
  artifacts:
    paths:
      - build
    expire_in: 1 week
    when: always

test-cleanup:
  extends: .k8s-test
  stage: .post
  when: manual
  script:
    - kubectl delete namespace ${NAMESPACE_SDP} --ignore-not-found
    - kubectl delete namespace ${NAMESPACE} --ignore-not-found
  environment:
    name: test/$CI_COMMIT_REF_NAME
    kubernetes:
      namespace: $NAMESPACE
    action: stop

# ============================================================================
# Build Helm chart
# ============================================================================

.build-helm:
  stage: build
  artifacts:
    paths:
      - sdp-*.tgz
    expire_in: 1 week

build-dev:
  extends: .build-helm
  script:
    - version=$(awk '/^version/ {print $2}' charts/sdp/Chart.yaml | tr -d '"')
    - helm package charts/sdp --dependency-update --version=${version}+${CI_COMMIT_SHORT_SHA}
  rules:
    - if: '$CI_COMMIT_TAG == null || $CI_COMMIT_TAG == ""'

build-release:
  extends: .build-helm
  script:
    - helm package charts/sdp --dependency-update
  only:
    variables:
       - $CI_COMMIT_MESSAGE =~ /^.+$/ # Confirm tag message exists
       - $CI_COMMIT_TAG =~ /^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/ #Confirm semantic versioning of tag
  except:
    - branches

# ============================================================================
# Publish Helm chart (tag only)
# ============================================================================

publish:
  stage: publish
  only:
    variables:
       - $CI_COMMIT_MESSAGE =~ /^.+$/ # Confirm tag message exists
       - $CI_COMMIT_TAG =~ /^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$/ #Confirm semantic versioning of tag
  except:
    - branches
  script:
    - curl --user ${HELM_USERNAME}:${HELM_PASSWORD} --upload-file sdp-*.tgz ${HELM_HOST}/repository/helm-chart/

# ============================================================================
# CI metrics
# ============================================================================
# Create Gitlab CI badges from CI metrics
# https://developer.skatelescope.org/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/post_step.yml'