{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}-console
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.console.image }}:{{ .Values.console.version }}
        imagePullPolicy: {{ .Values.console.imagePullPolicy }}
        name: console
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helm_deploy.namespace }}
      serviceAccountName: {{ include "sdp-prototype.fullname" . }}-helm
{{- end }}
