apiVersion: v2
name: sdp
version: 0.3.4
appVersion: "1.0"
description: Helm chart to deploy the SDP Prototype
home: https://developer.skatelescope.org/projects/sdp-prototype/
sources:
- https://gitlab.com/ska-telescope/sdp-integration
icon: http://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
- name: Mark Ashdown
  email: maja1@mrao.cam.ac.uk
dependencies:
- name: tango-base
  version: 0.2.8
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: tango-base.enabled,global.sub-system.tango-base.enabled
