system: sdp

# Global parameters
global: {}

# Tango dsconfig
dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.5.0
    pullPolicy: IfNotPresent

# Parameters for tango-base subchart
tango-base:
  enabled: true

# Configuration database
etcd:
  component: sdp-configuration-database
  subsystem: execution-control
  function: configuration
  domain: science-data-processing
  image: quay.io/coreos/etcd
  version: 3.3.25
  imagePullPolicy: IfNotPresent
  replicas: 1
  useOperator: false
  maxTxnOps: 1024

# Console
console:
  component: sdp-console
  subsystem: execution-control
  function: maintenance-control
  domain: science-data-processing
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-console
  version: 0.2.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  enabled: true

# Processing controller
proccontrol:
  component: sdp-processing-controller
  subsystem: execution-control
  function: PB-execution
  domain: science-data-processing
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-proccontrol
  version: 0.8.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  workflows:
    url: https://gitlab.com/ska-telescope/sdp/ska-sdp-science-pipelines/-/raw/master/workflows.json
    refresh: 300

# Helm deployment controller
helmdeploy:
  component: sdp-helm-deployer
  subsystem: execution-control
  function: runtime-deployment
  domain: science-data-processing
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-helmdeploy
  version: 0.7.2
  imagePullPolicy: IfNotPresent
  replicas: 1
  namespace: sdp
  prefix: ''
  createNamespace: false
  createClusterRole: false
  chart_repo:
    url: https://gitlab.com/ska-telescope/sdp/ska-sdp-helmdeploy-charts/-/raw/master/chart-repo/
    refresh: 300

# LMC (Tango devices)
lmc:
  component: sdp-lmc
  subsystem: execution-control
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-lmc
  version: 0.16.2
  imagePullPolicy: IfNotPresent
  enabled: true
  allCommandsHaveArgument: false
  prefix: test
  nsubarray: 1
  master:
    domain: sdp-monitoring
    function: sdp-central-control
  subarray:
    domain: subarray
    function: sdp-subarray-observation

nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
affinity: {}
tolerations: []
