
# Feature toggles
feature:
  # Tango devices connect to configuration DB?
  config-db: 1


# Helm deployment controller
helmdeploy:
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-helmdeploy
  version: 0.7.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  namespace: sdp
  chart_repo:
    url: https://gitlab.com/ska-telescope/sdp-helmdeploy-charts/-/raw/master/chart-repo/
    refresh: 300

# Configuration database
etcd:
  repository: quay.io/coreos/etcd
  version: "3.3"
  replicas: 1

# ds config
dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: latest
    pullPolicy: IfNotPresent

# Processing controller
proccontrol:
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-proccontrol
  version: 0.7.0
  replicas: 1
  resources: {}
  imagePullPolicy: IfNotPresent
  workflows:
    url: https://gitlab.com/ska-telescope/sdp-workflows-procfunc/-/raw/master/workflows.json
    refresh: 300

# LMC (Tango devices)
lmc:
  enabled: true
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-lmc
  version: 0.14.0
  imagePullPolicy: IfNotPresent

# Console
console:
  image: nexus.engageska-portugal.pt/sdp-prototype/ska-sdp-console
  version: 0.2.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  enabled: true

# Parameters for sub-chart
tango-base:
  tangotest:
    enabled: false
  itango:
    enabled: true
  jive:
    enabled: false
  logviewer:
    enabled: false

nameOverride: ""
fullnameOverride: ""
