{{- if .Values.console.enabled }}
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-sdp.name" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
    function: {{ .Values.console.function }}
    domain: {{ .Values.console.domain }}
    intent: production
spec:
  clusterIP: None
  selector:
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ska-sdp.name" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
    function: {{ .Values.console.function }}
    domain: {{ .Values.console.domain }}
    intent: production
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.console.component }}
      subsystem: {{ .Values.console.subsystem }}
  serviceName: {{ include "ska-sdp.name" . }}-console
  template:
    metadata:
      labels:
        {{- include "ska-sdp.labels" . | indent 8 }}
        component: {{ .Values.console.component }}
        subsystem: {{ .Values.console.subsystem }}
        function: {{ .Values.console.function }}
        domain: {{ .Values.console.domain }}
        intent: production
    spec:
      initContainers:
      {{- include "ska-sdp.wait-for-etcd" . | nindent 6 }}
      containers:
      - name: console
        image: {{ .Values.console.image }}:{{ .Values.console.version }}
        imagePullPolicy: {{ .Values.console.imagePullPolicy }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "ska-sdp.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helmdeploy.namespace }}
      serviceAccountName: {{ include "ska-sdp.name" . }}-helm
{{- end }}
