{{- if .Values.lmc.enabled }}
{{- $tangohost := default (printf "databaseds-tango-base-%s:10000" .Release.Name) .Values.global.tango_host }}
{{- $servers := dict }}
{{- /* Master */}}
{{- $name := "master" }}
{{- $instance := "0" }}
{{- $tangoname := printf "%s_sdp/elt/master" .Values.lmc.prefix }}
{{- $tangoconfig := dict }}
{{- $command := list "SDPMaster" }}
{{- $args := list $instance "-v4" }}
{{- $_ := set $servers "SDPMaster" (dict $instance (dict "SDPMaster" (dict $tangoname $tangoconfig))) }}
{{- $device := dict "name" $name "tangoname" $tangoname "command" $command "args" $args "domain" .Values.lmc.master.domain "function" .Values.lmc.master.function }}
{{- include "ska-sdp.lmc-device" (dict "device" $device "tangohost" $tangohost "root" .) }}
{{- /* Subarrays */}}
{{- $subarrays := dict }}
{{- range $i := until (int .Values.lmc.nsubarray) }}
{{- $number := add $i 1 }}
{{- $name := printf "subarray-%02d" $number}}
{{- $instance := printf "%02d" $number }}
{{- $tangoname := printf "%s_sdp/elt/subarray_%d" $.Values.lmc.prefix $number }}
{{- $tangoconfig := dict }}
{{- $command := list "SDPSubarray" }}
{{- $args := list $instance "-v4" }}
{{- $_ := set $subarrays $instance (dict "SDPSubarray" (dict $tangoname $tangoconfig)) }}
{{- $device := dict "name" $name "tangoname" $tangoname "command" $command "args" $args "domain" $.Values.lmc.subarray.domain "function" $.Values.lmc.subarray.function }}
{{- include "ska-sdp.lmc-device" (dict "device" $device "tangohost" $tangohost "root" $) }}
{{- end }}
{{- $_ := set $servers "SDPSubarray" $subarrays }}
{{- $config := dict "servers" $servers }}
{{- include "ska-sdp.lmc-config" (dict "config" $config "tangohost" $tangohost "root" .) }}
{{- end }}
