{{- if .Values.opinterface.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-sdp.name" . }}-opinterface
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.opinterface.component }}
    subsystem: {{ .Values.opinterface.subsystem }}
    function: {{ .Values.opinterface.function }}
    domain: {{ .Values.opinterface.domain }}
    intent: production
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    component: {{ .Values.opinterface.component }}
    subsystem: {{ .Values.opinterface.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ska-sdp.name" . }}-opinterface
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.opinterface.component }}
    subsystem: {{ .Values.opinterface.subsystem }}
    function: {{ .Values.opinterface.function }}
    domain: {{ .Values.opinterface.domain }}
    intent: production
spec:
  replicas: {{ .Values.opinterface.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.opinterface.component }}
      subsystem: {{ .Values.opinterface.subsystem }}
  serviceName: {{ include "ska-sdp.name" . }}-opinterface
  template:
    metadata:
      labels:
        {{- include "ska-sdp.labels" . | indent 8 }}
        component: {{ .Values.opinterface.component }}
        subsystem: {{ .Values.opinterface.subsystem }}
        function: {{ .Values.opinterface.function }}
        domain: {{ .Values.opinterface.domain }}
        intent: production
    spec:
      initContainers:
      {{- include "ska-sdp.wait-for-etcd" . | nindent 6 }}
      containers:
      - name: opinterface
        image: {{ .Values.opinterface.image }}:{{ .Values.opinterface.version }}
        imagePullPolicy: {{ .Values.opinterface.imagePullPolicy }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "ska-sdp.etcd-host" . }}
{{- end }}
