---
# Dummy Service to ensure Pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-sdp.name" . }}-proccontrol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.proccontrol.component }}
    subsystem: {{ .Values.proccontrol.subsystem }}
    function: {{ .Values.proccontrol.function }}
    domain: {{ .Values.proccontrol.domain }}
    intent: production
spec:
  clusterIP: None
  selector:
    component: {{ .Values.proccontrol.component }}
    subsystem: {{ .Values.proccontrol.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ska-sdp.name" . }}-proccontrol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-sdp.labels" . | indent 4 }}
    component: {{ .Values.proccontrol.component }}
    subsystem: {{ .Values.proccontrol.subsystem }}
    function: {{ .Values.proccontrol.function }}
    domain: {{ .Values.proccontrol.domain }}
    intent: production
spec:
  replicas: {{ .Values.proccontrol.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.proccontrol.component }}
      subsystem: {{ .Values.proccontrol.subsystem }}
  serviceName: {{ include "ska-sdp.name" . }}-proccontrol
  template:
    metadata:
      labels:
        {{- include "ska-sdp.labels" . | indent 8 }}
        component: {{ .Values.proccontrol.component }}
        subsystem: {{ .Values.proccontrol.subsystem }}
        function: {{ .Values.proccontrol.function }}
        domain: {{ .Values.proccontrol.domain }}
        intent: production
    spec:
      initContainers:
      {{- include "ska-sdp.wait-for-etcd" . | nindent 6 }}
      containers:
      - name: proccontrol
        image: {{ .Values.proccontrol.image }}:{{ .Values.proccontrol.version }}
        imagePullPolicy: {{ .Values.proccontrol.imagePullPolicy }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "ska-sdp.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helmdeploy.namespace }}
