{{- if .Values.console.enabled }}
# giving a dummy Service entry ensures that the single pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp.name" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
    function: {{ .Values.console.function }}
    domain: {{ .Values.console.domain }}
    intent: production
spec:
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234
  selector:
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sdp.name" . }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.console.component }}
    subsystem: {{ .Values.console.subsystem }}
    function: {{ .Values.console.function }}
    domain: {{ .Values.console.domain }}
    intent: production
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.console.component }}
      subsystem: {{ .Values.console.subsystem }}
  serviceName: {{ include "sdp.name" . }}-console
  template:
    metadata:
      labels:
        {{- include "sdp.labels" . | indent 8 }}
        component: {{ .Values.console.component }}
        subsystem: {{ .Values.console.subsystem }}
        function: {{ .Values.console.function }}
        domain: {{ .Values.console.domain }}
        intent: production
    spec:
      initContainers:
      {{- include "sdp.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.console.image }}:{{ .Values.console.version }}
        imagePullPolicy: {{ .Values.console.imagePullPolicy }}
        name: console
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helmdeploy.namespace }}
      serviceAccountName: {{ include "sdp.name" . }}-helm
{{- end }}
