{{- if .Values.helmdeploy.createNamespace }}
---
# Namespace for SDP dynamic deployments
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.helmdeploy.namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
{{- end }}
---
# giving a dummy Service entry ensures that the single pod is DNS addressable
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp.name" . }}-helmdeploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
spec:
  clusterIP: None
  ports:
  - name: dummy # Actually, no port is needed.
    port: 1234
    targetPort: 1234
  selector:
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sdp.name" . }}-helmdeploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
spec:
  replicas: {{ .Values.helmdeploy.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.helmdeploy.component }}
      subsystem: {{ .Values.helmdeploy.subsystem }}
  serviceName: {{ include "sdp.name" . }}-helmdeploy
  template:
    metadata:
      labels:
        {{- include "sdp.labels" . | indent 8 }}
        component: {{ .Values.helmdeploy.component }}
        subsystem: {{ .Values.helmdeploy.subsystem }}
        function: {{ .Values.helmdeploy.function }}
        domain: {{ .Values.helmdeploy.domain }}
        intent: production
    spec:
      initContainers:
      {{- include "sdp.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.helmdeploy.image }}:{{ .Values.helmdeploy.version }}
        imagePullPolicy: {{ .Values.helmdeploy.imagePullPolicy }}
        name: helmdeploy
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp.etcd-host" . }}
        - name: SDP_HELM_NAMESPACE
          value: {{ quote .Values.helmdeploy.namespace }}
        - name: SDP_CHART_REPO
          value: "{{ .Values.helmdeploy.chart_repo.url }}"
        - name: SDP_CHART_REPO_REFRESH
          value: "{{ .Values.helmdeploy.chart_repo.refresh }}"
        {{- include "sdp.http-proxy" . | nindent 8 }}
      serviceAccountName: {{ include "sdp.name" . }}-helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdp.name" . }}-helm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp.name" . }}-helm
  namespace: {{ .Values.helmdeploy.namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
subjects:
- kind: ServiceAccount
  name: {{ include "sdp.name" . }}-helm
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sdp.name" . }}-helm
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp.name" . }}-helm
  namespace: {{ .Values.helmdeploy.namespace }}
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]
- apiGroups: ["", "batch", "apps"]
  resources: ["deployments", "jobs", "pods", "configmaps",
              "persistentvolumeclaims", "services", "secrets"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
{{- if .Values.helmdeploy.createClusterRole }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp.name" . }}-helm-global
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
subjects:
- kind: ServiceAccount
  name: {{ include "sdp.name" . }}-helm
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "sdp.name" . }}-helm-global
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sdp.name" . }}-helm-global
  labels:
    {{- include "sdp.labels" . | indent 4 }}
    component: {{ .Values.helmdeploy.component }}
    subsystem: {{ .Values.helmdeploy.subsystem }}
    function: {{ .Values.helmdeploy.function }}
    domain: {{ .Values.helmdeploy.domain }}
    intent: production
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
{{- end }}
